name: next_byte
description: Next_Byte A Video Sharing Flutter App. using Firebase and Firestore Video Hosting as Backend.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_circular_progress_bar:
  get:
  intl:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  http:
  url_launcher:
  google_sign_in:
  flutter_easyloading:
  fluttertoast:
  hive:
  hive_flutter:
  #carousel_slider:
  #shared_preferences:
  image_picker:
  #intl_phone_number_input:
  #pinput:
  #pin_code_fields:
  flutter_launcher_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

#flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logos/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logos/logo.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
