// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxg_xSDERMd2veMer4QySnAVnl212jYk',
    appId: '1:634713349445:web:a64fbf804da490d959722c',
    messagingSenderId: '634713349445',
    projectId: 'next-byte',
    authDomain: 'next-byte.firebaseapp.com',
    storageBucket: 'next-byte.appspot.com',
    measurementId: 'G-VMGDVZV379',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxZbdRVhPz3A1bknMR9qnXuYmPvD2LWk',
    appId: '1:634713349445:android:4922c545050b7f4359722c',
    messagingSenderId: '634713349445',
    projectId: 'next-byte',
    storageBucket: 'next-byte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHprNYCeCq6DwvCHZjQqtSW_QXKlo9cxg',
    appId: '1:634713349445:ios:ce4a813331f0e3dc59722c',
    messagingSenderId: '634713349445',
    projectId: 'next-byte',
    storageBucket: 'next-byte.appspot.com',
    androidClientId: '634713349445-vemb5thkh46ps9d8124n6gfsentimjc8.apps.googleusercontent.com',
    iosClientId: '634713349445-846fc1ei68cetdvmtobt70bkbf4f7f7n.apps.googleusercontent.com',
    iosBundleId: 'com.nextdigit.nextByte',
  );
}
